# vector space

In [2]:
#A vector space is a set of vectors where you can add vectors and multiply them by scalars, and the result still belongs to the space.
#ex : v1=(1,2) - v2=(3,4) => all in R^2 vector space

# vector span

In [5]:
#Given a set of vectors v1,v2,vk ... The span is the set of all possible linear combinations of these vectors. 
#the span tells us how far we can cover the space or reach all the possible vectors in the vector space by addition and scalling
#to cover up R^n span we need n linearly independent vectors 

# linear independency

In [4]:
# we can call N vector as linear independent if none of them can be obtained from the others using addition and scalling
# this can be checked using Rank (RREF) or Determinant in case of square matrix

In [120]:
import numpy as np
v=np.array ([4,1])
u=np.array([0,-2])
vector_span = np.array([v,u]).T
det = np.linalg.det(vector_span)
if det==0:
    print("linear dependent")
else :
    print("linear independent")

linear independent


In [121]:
import sympy as sm
span = sm.Matrix(vector_span)
span.rref()         # rank = 2 (two pivots)  

(Matrix([
 [1, 0],
 [0, 1]]),
 (0, 1))

In [122]:
# u,v already covers R2 vetor space 
# if another vector[7,4] is used it would be redundunt (can be formed as a linear combination of the other two)
redundunt_span = sm.Matrix([[4,0,7],[1,-2,4]])
redundunt_span.rref()     # rank = 2 (there is a vetor that can be linear combination of the two others)
# redundunt vector = 7*v + 3*u

(Matrix([
 [1, 0,  7/4],
 [0, 1, -9/8]]),
 (0, 1))

In [124]:
7/4*v + -9/8*u

array([7., 4.])

# changing basis

In [125]:
# expressing the same vector with respect to another set of vector span
# ex : [5,3] is expressed with respect to e1,e2 .. changing basis to v,u will be
P=np.array([v,u]).T
v1=np.array([5,3])
v2=np.linalg.inv(P) @ v1
print ("v1 in respect to v and u is :" ,v2)
restored = P@v2
if restored.all() == v1.all():
    print ("v1 restoed successfully")

v1 in respect to v and u is : [ 1.25  -0.875]
v1 restoed successfully


#### Transformation in a changed basis

In [126]:
# P@v2 to restore to e basis ---T@P@v2 for the transformation --- inv(P)@T@P@v2 to back to u,v basis
#soo the final equation is : inv(P)@T@P@
#inverse is too computationally expensive what takes us to orthogonaliztion (then P inverse = P transpose)

# orthonormalization

In [127]:
#assume q1 is v -- get the Perpendicular component of u over v by subtracting u - proj on v ... repeat in case of more than 2
#or use QR decomposition

###### manually

In [128]:
q1=v/np.linalg.norm(v)
u_proj_over_v = (np.dot(u,v)/np.dot(v,v))*v
Perpendicular_component = u-u_proj_over_v
q2=Perpendicular_component/np.linalg.norm(Perpendicular_component)
print(np.array([q1,q2]))
q1@q2

[[ 0.9701425   0.24253563]
 [ 0.24253563 -0.9701425 ]]


0.0

##### QR

In [129]:
Q, R = np.linalg.qr(vector_span)
print (Q)

[[-0.9701425  -0.24253563]
 [-0.24253563  0.9701425 ]]


In [131]:
#QR and gramshmdit gives us E basis with respect to v,u Basis
#so Transformation will be Q@T@inv(Q) -- inv(Q) = Q.T (orthonormal) => Transformation = Q@T@Q.T